// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgxctmbpxjqthkuvotlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZneGN0bWJweGpxdGhrdXZvdGxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTY0MjUsImV4cCI6MjA2NTk5MjQyNX0.t5abb0-g2dbWHh9ZJBOgymjKTs9iH6jZ_4VB241ToFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);